from enum import Enum


class State(str, Enum):
    GREET = "GREET"
    DISCLAIMER_AWAIT_ACK = "DISCLAIMER_AWAIT_ACK"
    INTENT_ROUTING = "INTENT_ROUTING"
    BOOK_TOPIC = "BOOK_TOPIC"
    BOOK_TIME_PREFERENCE = "BOOK_TIME_PREFERENCE"
    BOOK_OFFER_SLOTS = "BOOK_OFFER_SLOTS"
    BOOK_CONFIRM = "BOOK_CONFIRM"
    BOOK_EXECUTE_MCP = "BOOK_EXECUTE_MCP"
    CLOSE = "CLOSE"
    RESCHEDULE_COLLECT_CODE = "RESCHEDULE_COLLECT_CODE"
    RESCHEDULE_OFFER_SLOTS = "RESCHEDULE_OFFER_SLOTS"
    RESCHEDULE_CONFIRM = "RESCHEDULE_CONFIRM"
    CANCEL_COLLECT_CODE = "CANCEL_COLLECT_CODE"
    CANCEL_CONFIRM = "CANCEL_CONFIRM"
    PREPARE_TOPIC_OR_GENERIC = "PREPARE_TOPIC_OR_GENERIC"
    AVAILABILITY_QUERY = "AVAILABILITY_QUERY"
    ERROR_RECOVER = "ERROR_RECOVER"
